library(readr)
library(tidyverse)
mort_data <- read_csv("indicatordeadkids35.csv")
head(mort_data)
mort_data <- mort_data %>% dplyr::rename(country = "...1")
head(mort_data)
long_mort <- mort_data %>% pivot_longer(cols = -country, names_to = "year", values_to = "mort")
head(long_mort)
long_mort <- long_mort %>% mutate(year = as.numeric(year))
head(long_mort)
names(long_mort)
colnames(long_mort)
unique(long_mort$country)
long_sweden <- long_mort %>% filter(country == "Sweden")
head(long_sweden)
g = ggplot(data = long_sweden, aes(x = year, y = mort))
g
gpoints = g + geom_point()
gpoints
g+geom_line()
g+geom_line() + geom_smooth()
rm(hfe_data)
install.packages("Hmisc")