library(readr)
pupae <- read_csv("pupae.csv")
str(pupae)
pupae$T_treatment <- as.factor(pupae$T_treatment)
pupae$CO2_treatment <- as.factor(pupae$CO2_treatment)
str(pupae)
levels(pupae$CO2_treatment)
pupaeamb <- subset(pupae, T_treatment == "ambient")
table(pupaeamb$T_treatment)
pupae_amb2 <- droplevels(pupaeamb)
table(pupae_amb2$T_treatment)
levels(pupae$T_treatment) <- c("ambient", "ambient + 3C")
table(pupae$T_treatment)
levels(pupae$T_treatment)[1] <- "control"
table(pupae$T_treatment)
subset(pupae, PupalWeight > 0.2 & Frass > 0.1)
View(pupae)
myvec1 <-c(11,13,5,6,NA,9)
is.na(myvec1)
sum(is.na(myvec1))
which(is.na(myvec1))
datavec <-c(2,-9999,100,3,-9999,5)
datavec[datavec == -9999] <- NA
datavec
log(-1)
summary(pupae)
sum(is.na(pupae))
pupae$T_CO2 <- with(pupae, paste(T_treatment, CO2_treatment, sep = "-"))
head(pupae$T_CO2)
